`timescale 1ns/100ps

// FENICS shaper, F34 design (Simulacao_MinBias/34_iir_40mhz).
//
// GENERATED by gerar_verilog.py from outputs/estrutura_fir_iir.npz.
// Do not edit the coefficients by hand: rerun the generator instead.
//
// Structure: a 13-tap FIR head for the 8 fast poles (tau 20-40 ns, which
// decay within 1-2 samples at 40 MHz) plus 5 IIR sections for the 6 slow
// poles. The FIR head exists because two fast poles carry residues of
// +527.97 and -527.79 that nearly cancel: summing them once at design time,
// in float64, keeps that cancellation out of the runtime datapath.
//
// First-order sections use the LEAKY form  y += k*(G*x - y). In steady state
// k*(G*x - y) = 0, so the DC gain is EXACTLY G no matter how coarsely k is
// quantized; quantizing k only shifts the time constant. That property is
// what lets the tau = 10.1 ms section IMPOSE a total DC gain of exactly
// zero (its G is computed last, after every other coefficient is quantized).
// Without it the simulator would produce a baseline sag that the real system
// does not have (-0.0167 at 5% occupancy).
//
// Second-order sections use the COUPLED (Gold-Rader) form with state (u,v).
// The naive delta form is unusable here: its DC gain depends on d1+d2, which
// is itself a cancellation (+4.75e-5 and -4.75e-5 for the 1.053 ms pair).
//
// ROUNDING: every product shift adds MEIO = 2**(W_COEF-1) and every output
// shift adds half an LSB. A plain arithmetic shift is FLOOR, so a state
// parked just below zero would emit -1 LSB on every sample. Measured in
// steady state the difference is ~1e-10 of peak, so this is fixed-point
// hygiene rather than a fix for a real defect -- but it costs one adder per
// section, so it stays.
//
// All coefficients are 2-term CSD constants, so each constant multiply below
// synthesizes to two shifts and one add: no DSP blocks, no generic
// multipliers. F34 cost estimate: ~92 adders, about 1797 1-bit full adders.
//
// Validated against the F34 target in integer arithmetic, identical to
// plot_float_vs_circuito.py: shape error 0.0258% of peak,
// steady-state DC gain -1.8e-07.
//
// NOTE: the sampling phase is FIXED at 1.4128 ns after the bunch crossing.
// This filter reproduces ONE phase. Arbitrary phases (jitter, TOF) would
// need a polyphase bank: N coefficient sets, same arithmetic.
module shaper_fenics_f34
#(
	parameter BITS_IN = 34,
	parameter G_OUT_LOG = 10
)
(
	input  clock, rst,
	input  signed [BITS_IN-1:0] in,
	output signed [BITS_IN+16:0] out
);

localparam integer W_COEF  = 30;   // coefficient fraction bits
localparam integer B_C     = 12;   // FIR tap fraction bits
localparam integer N_DELAY = 3;    // shared delay of the slow sections
// State width is sized PER SECTION: a section holds at most |G|*|x|*2**EX,
// so it needs (BITS_IN-1) + EX + ceil(log2|G|) + 1 bits, plus guard for the
// transient. A single uniform width would overflow the tau = 10.1 ms section
// at small BITS_IN (it carries the largest EX) while wasting bits on the fast
// ones. WP is the product width: the coefficient adds W_COEF fraction bits.
localparam signed [W_COEF:0] MEIO = 1 <<< (W_COEF-1);

// ---------------------------------------------------------- FIR head -----
localparam signed [B_C+1:0] TAP00 = 0;
localparam signed [B_C+1:0] TAP01 = 0;
localparam signed [B_C+1:0] TAP02 = 0;
localparam signed [B_C+1:0] TAP03 = 1555;
localparam signed [B_C+1:0] TAP04 = 4101;
localparam signed [B_C+1:0] TAP05 = 1960;
localparam signed [B_C+1:0] TAP06 = 267;
localparam signed [B_C+1:0] TAP07 = -55;
localparam signed [B_C+1:0] TAP08 = -51;
localparam signed [B_C+1:0] TAP09 = -5;
localparam signed [B_C+1:0] TAP10 = -42;
localparam signed [B_C+1:0] TAP11 = -20;
localparam signed [B_C+1:0] TAP12 = -8;

reg signed [BITS_IN-1:0] d [0:12];
integer i;
always @(posedge clock or posedge rst) begin
	if (rst) begin
		for (i = 0; i < 13; i = i + 1) d[i] <= 0;
	end else begin
		d[0] <= in;
		for (i = 1; i < 13; i = i + 1) d[i] <= d[i-1];
	end
end

wire signed [BITS_IN+B_C+4:0] fir_acc =
	  TAP00*d[0]
	+ TAP01*d[1]
	+ TAP02*d[2]
	+ TAP03*d[3]
	+ TAP04*d[4]
	+ TAP05*d[5]
	+ TAP06*d[6]
	+ TAP07*d[7]
	+ TAP08*d[8]
	+ TAP09*d[9]
	+ TAP10*d[10]
	+ TAP11*d[11]
	+ TAP12*d[12];
// FIR taps are Q(B_C); bring them down to the Q(G_OUT_LOG) output scale.
wire signed [BITS_IN+16:0] fir_out =
	(fir_acc + (1 <<< (B_C-G_OUT_LOG-1))) >>> (B_C-G_OUT_LOG);

// ------------------------------- shared delay feeding the slow sections ---
// The pulse only starts at sample N_DELAY and the FIR head already carries
// those zeros in its taps. Feeding the slow sections with `in` directly
// advances them by N_DELAY samples: 0.13% error instead of ~1e-4%.
reg signed [BITS_IN-1:0] xd [0:2];
always @(posedge clock or posedge rst) begin
	if (rst) begin
		for (i = 0; i < 3; i = i + 1) xd[i] <= 0;
	end else begin
		xd[0] <= in;
		for (i = 1; i < 3; i = i + 1) xd[i] <= xd[i-1];
	end
end
wire signed [BITS_IN-1:0] xs = xd[2];

// ---- leaky section 0: tau=16.6us
//      k = 1.464844e-03 (+2^-9 -2^-11)   G = -0.253906250
localparam integer EX_L0 = 14;
localparam signed [W_COEF+1:0] K_L0 = 1572864;
localparam signed [W_COEF+1:0] G_L0 = -272629760;
localparam integer WS_L0 = BITS_IN + EX_L0 + 4;
localparam integer WP_L0 = WS_L0 + W_COEF + 2;
reg  signed [WS_L0-1:0] acc_L0 = 0;
wire signed [WP_L0-1:0] tgt_L0 = (G_L0 * (xs <<< EX_L0) + MEIO) >>> W_COEF;
wire signed [WP_L0-1:0] inc_L0 = (K_L0 * (tgt_L0 - acc_L0) + MEIO) >>> W_COEF;
always @(posedge clock or posedge rst)
	if (rst) acc_L0 <= 0; else acc_L0 <= acc_L0 + inc_L0;
wire signed [BITS_IN+16:0] out_L0 =
	(acc_L0 + (1 <<< (EX_L0-G_OUT_LOG-1))) >>> (EX_L0-G_OUT_LOG);

// ---- leaky section 1: tau=48.4us
//      k = 5.187988e-04 (+2^-11 +2^-15)   G = -1.992187500
localparam integer EX_L1 = 15;
localparam signed [W_COEF+1:0] K_L1 = 557056;
localparam signed [W_COEF+1:0] G_L1 = -2139095040;
localparam integer WS_L1 = BITS_IN + EX_L1 + 4;
localparam integer WP_L1 = WS_L1 + W_COEF + 2;
reg  signed [WS_L1-1:0] acc_L1 = 0;
wire signed [WP_L1-1:0] tgt_L1 = (G_L1 * (xs <<< EX_L1) + MEIO) >>> W_COEF;
wire signed [WP_L1-1:0] inc_L1 = (K_L1 * (tgt_L1 - acc_L1) + MEIO) >>> W_COEF;
always @(posedge clock or posedge rst)
	if (rst) acc_L1 <= 0; else acc_L1 <= acc_L1 + inc_L1;
wire signed [BITS_IN+16:0] out_L1 =
	(acc_L1 + (1 <<< (EX_L1-G_OUT_LOG-1))) >>> (EX_L1-G_OUT_LOG);

// ---- leaky section 2: tau=10.1ms (fecha)
//      k = 2.384186e-06 (+2^-19 +2^-21)   G = +0.267446307   <-- G IMPOSED: total DC gain = 0
localparam integer EX_L2 = 23;
localparam signed [W_COEF+1:0] K_L2 = 2560;
localparam signed [W_COEF+1:0] G_L2 = 287168285;
localparam integer WS_L2 = BITS_IN + EX_L2 + 4;
localparam integer WP_L2 = WS_L2 + W_COEF + 2;
reg  signed [WS_L2-1:0] acc_L2 = 0;
wire signed [WP_L2-1:0] tgt_L2 = (G_L2 * (xs <<< EX_L2) + MEIO) >>> W_COEF;
wire signed [WP_L2-1:0] inc_L2 = (K_L2 * (tgt_L2 - acc_L2) + MEIO) >>> W_COEF;
always @(posedge clock or posedge rst)
	if (rst) acc_L2 <= 0; else acc_L2 <= acc_L2 + inc_L2;
wire signed [BITS_IN+16:0] out_L2 =
	(acc_L2 + (1 <<< (EX_L2-G_OUT_LOG-1))) >>> (EX_L2-G_OUT_LOG);

// ---- coupled (Gold-Rader) section 0: tau=1052.7us (par)
//      c = 1-Re(z) = 2.288818e-05   s = Im(z) = 4.917383e-07
localparam integer EX_A0 = 20;
localparam signed [W_COEF+1:0] C_A0 = 24576;
localparam signed [W_COEF+1:0] S_A0 = 528;
localparam signed [W_COEF+1:0] RA_A0 = 1280;
localparam signed [W_COEF+1:0] RB_A0 = -40;
localparam integer WS_A0 = BITS_IN + EX_A0 + 4;
localparam integer WP_A0 = WS_A0 + W_COEF + 2;
reg  signed [WS_A0-1:0] u_A0 = 0, v_A0 = 0;
wire signed [WP_A0-1:0] xn_A0 = xs <<< EX_A0;
wire signed [WP_A0-1:0] un_A0 = u_A0
	- ((C_A0*u_A0 + MEIO) >>> W_COEF) - ((S_A0*v_A0 + MEIO) >>> W_COEF)
	+ ((RA_A0*xn_A0 + MEIO) >>> W_COEF);
wire signed [WP_A0-1:0] vn_A0 = v_A0
	- ((C_A0*v_A0 + MEIO) >>> W_COEF) + ((S_A0*u_A0 + MEIO) >>> W_COEF)
	+ ((RB_A0*xn_A0 + MEIO) >>> W_COEF);
always @(posedge clock or posedge rst) begin
	if (rst) begin u_A0 <= 0; v_A0 <= 0; end
	else     begin u_A0 <= un_A0; v_A0 <= vn_A0; end
end
wire signed [BITS_IN+16:0] out_A0 =
	((u_A0 <<< 1) + (1 <<< (EX_A0-G_OUT_LOG-1))) >>> (EX_A0-G_OUT_LOG);

// ---- coupled (Gold-Rader) section 1: tau=21.3us (par)
//      c = 1-Re(z) = 1.220703e-03   s = Im(z) = 1.708984e-03
localparam integer EX_A1 = 14;
localparam signed [W_COEF+1:0] C_A1 = 1310720;
localparam signed [W_COEF+1:0] S_A1 = 1835008;
localparam signed [W_COEF+1:0] RA_A1 = 57344;
localparam signed [W_COEF+1:0] RB_A1 = 49152;
localparam integer WS_A1 = BITS_IN + EX_A1 + 4;
localparam integer WP_A1 = WS_A1 + W_COEF + 2;
reg  signed [WS_A1-1:0] u_A1 = 0, v_A1 = 0;
wire signed [WP_A1-1:0] xn_A1 = xs <<< EX_A1;
wire signed [WP_A1-1:0] un_A1 = u_A1
	- ((C_A1*u_A1 + MEIO) >>> W_COEF) - ((S_A1*v_A1 + MEIO) >>> W_COEF)
	+ ((RA_A1*xn_A1 + MEIO) >>> W_COEF);
wire signed [WP_A1-1:0] vn_A1 = v_A1
	- ((C_A1*v_A1 + MEIO) >>> W_COEF) + ((S_A1*u_A1 + MEIO) >>> W_COEF)
	+ ((RB_A1*xn_A1 + MEIO) >>> W_COEF);
always @(posedge clock or posedge rst) begin
	if (rst) begin u_A1 <= 0; v_A1 <= 0; end
	else     begin u_A1 <= un_A1; v_A1 <= vn_A1; end
end
wire signed [BITS_IN+16:0] out_A1 =
	((u_A1 <<< 1) + (1 <<< (EX_A1-G_OUT_LOG-1))) >>> (EX_A1-G_OUT_LOG);

// ------------------------------------------------------------- output ----
assign out = fir_out
	+ out_L0
	+ out_L1
	+ out_L2
	+ out_A0
	+ out_A1;

endmodule
