`timescale 1ns/100ps

// CSA + CR-4RC shaper: the generic "paper simulator" pulse.
//
// GENERATED by emitir_verilog.py (research vault, phase F03/F37 of the
// Simulador_Pulsos_FPGA line). Do not edit coefficients by hand: rerun the
// generator instead.
//
// The characteristic pulse is the EXACT readout chain of the group's papers
// (Electronics 14:493 signal generator): bi-exponential input (1/5 ns), CSA
// with a 51 ns feedback pole, and an unbuffered CR-4RC ladder with a 500 us
// CR and four 5 ns RC stages. Pulse: peak at 60.1 ns (on sample 2, sampling
// phase 10.10 ns), FWHM 114 ns, zero DC gain in continuous time, -2.5e-4
// tail out to ~0.5 ms.
//
// Structure: a 4-tap FIR head absorbs the 5 fast poles (their z-poles die
// within 2 samples; this includes the near-equal pair whose +-3.06e4 partial
// -fraction residues would cancel catastrophically in raw parallel fixed
// point) + 3 first-order direct-form IIR sections (tau = 500 us, 51 ns,
// 41.5 ns). Every arithmetic shift rounds to nearest (adds half an LSB
// first). Shape error of the integer model vs the exact kernel: 1e-7 of the
// peak (impulse 4095); 2.6e-6 for a small impulse (190).
//
// NOTE the kernel's SAMPLE SUM is -0.02466, not zero: the continuous pulse
// has exactly zero DC gain, but it is fast (5 ns edges), so summing samples
// at 25 ns aliases the 40 MHz harmonics (Poisson summation). The steady
// baseline is therefore -0.02466 * mean(input): that is the baseline-shift
// physics of the sampled chain that the papers describe, not a fixed-point
// artifact, and it is NOT removed here.
//
// Latency: 1 cycle (registered output adder): h[0] appears one clock after
// the input impulse.
//
// WARNING: the constants below bake in G_OUT_LOG = 10 (output scale 2**10,
// the HITS convention shared by the other shapers). The parameter exists for
// interface compatibility only.
module shaper_csa_cr4rc
#(
	parameter BITS_IN = 34,
	parameter G_OUT_LOG = 10
)
(
	input  clock, rst,
	input  signed [BITS_IN-1:0] in,
	output signed [BITS_IN+16:0] out
);

localparam integer SC = 30;      // fraction bits of the feedback coefficients
localparam integer F  = 20;       // fraction bits of the section states
localparam integer BC = 18;      // fraction bits of the FIR taps
localparam integer WY = BITS_IN + 40;             // section state width
localparam integer WS = WY + 2;                   // final adder width

// feedback coefficients q_k * 2**SC (tau = 500 us, 51 ns, 41.5 ns)
localparam signed [SC+1:0] Q0 = 1073688140;
localparam signed [SC+1:0] Q1 = 657673614;
localparam signed [SC+1:0] Q2 = 587460796;
// input gains r_k * 2**(G_OUT_LOG+F)
localparam signed [35:0] R0 = -273473;
localparam signed [35:0] R1 = 15294322478;
localparam signed [35:0] R2 = -15580950631;
// FIR taps c_m * 2**(G_OUT_LOG+BC) (the 5 fast poles, collapsed)
localparam signed [27:0] T0 = 92737730;
localparam signed [27:0] T1 = 1545777;
localparam signed [27:0] T2 = 16631;
localparam signed [27:0] T3 = 154;

localparam signed [SC:0] MEIO_SC = 1 <<< (SC - 1);
localparam signed [F:0]  MEIO_F  = 1 <<< (F - 1);

reg signed [BITS_IN-1:0] x1 = 0, x2 = 0, x3 = 0;   // FIR delay line
reg signed [WY-1:0] y0 = 0, y1 = 0, y2 = 0;        // IIR section states
reg signed [BITS_IN+16:0] acc = 0;                 // registered, rounded output

// FIR head (wide targets so the products keep every bit)
wire signed [BC+BITS_IN+12:0] fir =
	T0 * in + T1 * x1 + T2 * x2 + T3 * x3;

// section k: y_k[n] = R_k*x[n] + round(Q_k * y_k[n-1] / 2**SC)
wire signed [SC+WY+1:0] p0 = Q0 * y0, p1 = Q1 * y1, p2 = Q2 * y2;
wire signed [WY-1:0] y0n = R0 * in + ((p0 + MEIO_SC) >>> SC);
wire signed [WY-1:0] y1n = R1 * in + ((p1 + MEIO_SC) >>> SC);
wire signed [WY-1:0] y2n = R2 * in + ((p2 + MEIO_SC) >>> SC);

// sum of the NEW states + the FIR aligned from BC to F fraction bits
wire signed [WS-1:0] soma =
	y0n + y1n + y2n + ((fir <<< (F - BC)));

always @(posedge clock or posedge rst) begin
	if (rst) begin
		x1 <= 0; x2 <= 0; x3 <= 0;
		y0 <= 0; y1 <= 0; y2 <= 0;
		acc <= 0;
	end
	else begin
		x1 <= in; x2 <= x1; x3 <= x2;
		y0 <= y0n; y1 <= y1n; y2 <= y2n;
		acc <= (soma + MEIO_F) >>> F;
	end
end

assign out = acc;

endmodule
